import { commands } from './data/commands.js';
import { getLanguage, t } from './i18n.js';
const categoryLabels={
  en:{Navigation:'Navigation',Directories:'Directories',Files:'Files',Text:'Text',Search:'Search',Processes:'Processes',Permissions:'Permissions',Users:'Users',System:'System',Storage:'Storage',Network:'Network',Archives:'Archives',Packages:'Packages',Administration:'Administration'},
  pt:{Navigation:'Navegação',Directories:'Diretórios',Files:'Arquivos',Text:'Texto',Search:'Busca',Processes:'Processos',Permissions:'Permissões',Users:'Usuários',System:'Sistema',Storage:'Armazenamento',Network:'Rede',Archives:'Arquivos compactados',Packages:'Pacotes',Administration:'Administração'}
};

const coreutilsReference='https://www.gnu.org/software/coreutils/manual/coreutils.html';
const commandReferences={
  pwd:coreutilsReference,ls:coreutilsReference,mkdir:coreutilsReference,touch:coreutilsReference,cat:coreutilsReference,head:coreutilsReference,tail:coreutilsReference,whoami:coreutilsReference,id:coreutilsReference,uname:coreutilsReference,df:coreutilsReference,du:coreutilsReference,chmod:coreutilsReference,chown:coreutilsReference,rm:coreutilsReference,dd:coreutilsReference,
  grep:'https://www.gnu.org/software/grep/manual/grep.html',find:'https://www.gnu.org/software/findutils/manual/html_mono/find.html',ps:'https://man7.org/linux/man-pages/man1/ps.1.html',kill:'https://man7.org/linux/man-pages/man1/kill.1.html',lsblk:'https://man7.org/linux/man-pages/man8/lsblk.8.html',ip:'https://man7.org/linux/man-pages/man8/ip.8.html',ping:'https://man7.org/linux/man-pages/man8/ping.8.html',ssh:'https://man.openbsd.org/ssh',apt:'https://www.debian.org/doc/manuals/debian-reference/ch02.en.html',dnf:'https://docs.fedoraproject.org/',pacman:'https://man.archlinux.org/man/pacman.8',systemctl:'https://www.freedesktop.org/software/systemd/man/latest/systemctl.html',journalctl:'https://www.freedesktop.org/software/systemd/man/latest/journalctl.html',tar:'https://www.gnu.org/software/tar/manual/tar.html',mkfs:'https://man7.org/linux/man-pages/man8/mkfs.8.html',fdisk:'https://man7.org/linux/man-pages/man8/fdisk.8.html'
};

const levelLabels={en:{Beginner:'Beginner',Intermediate:'Intermediate',Advanced:'Advanced'},pt:{Beginner:'Iniciante',Intermediate:'Intermediário',Advanced:'Avançado'}};
export function initCommandExplorer(){
  const grid=document.querySelector('#commandGrid'),search=document.querySelector('#commandSearch'),category=document.querySelector('#commandCategory');
  const localize=v=>typeof v==='string'?v:(v?.[getLanguage()]??v?.en??'');
  function buildCategories(){const selected=category.value||'all';category.replaceChildren();const all=document.createElement('option');all.value='all';all.textContent=t('allCategories');category.append(all);[...new Set(commands.map(c=>c.category))].sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=categoryLabels[getLanguage()][c]||c;category.append(o);});category.value=[...category.options].some(o=>o.value===selected)?selected:'all';}
  function render(){const q=search.value.trim().toLowerCase(),cat=category.value;const lang=getLanguage();const filtered=commands.filter(c=>(cat==='all'||c.category===cat)&&(!q||[c.name,c.category,localize(c.description),c.example].join(' ').toLowerCase().includes(q)));grid.replaceChildren();if(!filtered.length){const e=document.createElement('div');e.className='empty-state';e.textContent=t('noCommands');grid.append(e);return;}filtered.forEach(c=>{const card=document.createElement('article');card.className='command-card';const head=document.createElement('header');const h=document.createElement('h3');h.textContent=c.name;const badge=document.createElement('span');badge.className=`badge ${c.risk?'risk':''}`;badge.textContent=c.risk?t('risk'):(levelLabels[lang][c.level]||c.level);head.append(h,badge);const p=document.createElement('p');p.textContent=localize(c.description);const syntax=document.createElement('div');syntax.className='command-syntax';syntax.innerHTML=`<span>${t('syntaxLabel')}</span><code></code>`;syntax.querySelector('code').textContent=c.syntax;const pre=document.createElement('pre');pre.textContent=c.example;const ref=document.createElement('a');ref.className='command-reference';ref.href=commandReferences[c.name]||'https://man7.org/linux/man-pages/';ref.target='_blank';ref.rel='noopener noreferrer';ref.textContent=`${t('docsLink')} ↗`;card.append(head,p,syntax,pre);if(c.risk){const r=document.createElement('div');r.className='risk-note';r.textContent=`⚠ ${localize(c.risk)}`;card.append(r);}card.append(ref);grid.append(card);});}
  search.addEventListener('input',render);category.addEventListener('change',render);window.addEventListener('academy:language',()=>{buildCategories();render();});buildCategories();render();return commands;
}
