const categoryLabels={
  en:{Navigation:'Navigation',Directories:'Directories',Files:'Files',Text:'Text',Search:'Search',Processes:'Processes',Permissions:'Permissions',Users:'Users',System:'System',Storage:'Storage',Network:'Network',Archives:'Archives',Packages:'Packages',Administration:'Administration'},
  pt:{Navigation:'Navegação',Directories:'Diretórios',Files:'Arquivos',Text:'Texto',Search:'Busca',Processes:'Processos',Permissions:'Permissões',Users:'Usuários',System:'Sistema',Storage:'Armazenamento',Network:'Rede',Archives:'Arquivos compactados',Packages:'Pacotes',Administration:'Administração'}
};

const levelLabels={en:{Beginner:'Beginner',Intermediate:'Intermediate',Advanced:'Advanced'},pt:{Beginner:'Iniciante',Intermediate:'Intermediário',Advanced:'Avançado'}};
function initCommandExplorer(){
  const grid=document.querySelector('#commandGrid'),search=document.querySelector('#commandSearch'),category=document.querySelector('#commandCategory');
  const localize=v=>typeof v==='string'?v:(v?.[getLanguage()]??v?.en??'');
  function buildCategories(){const selected=category.value||'all';category.replaceChildren();const all=document.createElement('option');all.value='all';all.textContent=t('allCategories');category.append(all);[...new Set(commands.map(c=>c.category))].sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=categoryLabels[getLanguage()][c]||c;category.append(o);});category.value=[...category.options].some(o=>o.value===selected)?selected:'all';}
  function render(){const q=search.value.trim().toLowerCase(),cat=category.value;const lang=getLanguage();const filtered=commands.filter(c=>(cat==='all'||c.category===cat)&&(!q||[c.name,c.category,localize(c.description),c.example].join(' ').toLowerCase().includes(q)));grid.replaceChildren();if(!filtered.length){const e=document.createElement('div');e.className='empty-state';e.textContent=t('noCommands');grid.append(e);return;}filtered.forEach(c=>{const card=document.createElement('article');card.className='command-card';const head=document.createElement('header');const h=document.createElement('h3');h.textContent=c.name;const badge=document.createElement('span');badge.className=`badge ${c.risk?'risk':''}`;badge.textContent=c.risk?t('risk'):(levelLabels[lang][c.level]||c.level);head.append(h,badge);const p=document.createElement('p');p.textContent=localize(c.description);const syntax=document.createElement('div');syntax.className='command-syntax';syntax.innerHTML=`<span>${t('syntaxLabel')}</span><code></code>`;syntax.querySelector('code').textContent=c.syntax;const pre=document.createElement('pre');pre.textContent=c.example;const reference=getCommandReference(c.name);card.append(head,p,syntax,pre);if(c.risk){const r=document.createElement('div');r.className='risk-note';r.textContent=`⚠ ${localize(c.risk)}`;card.append(r);}const refWrap=document.createElement('div');refWrap.className='command-reference-wrap';if(reference){const ref=document.createElement('a');ref.className='command-reference';ref.href=reference.url;ref.target='_blank';ref.rel='noopener noreferrer';ref.textContent=`${getReferenceLabel(reference.type)} ↗`;ref.setAttribute('aria-label',`${getReferenceLabel(reference.type)}: ${c.name} — ${reference.provider}`);const source=document.createElement('small');source.className='command-reference-source';source.textContent=`${getReferenceSourceLabel()}: ${reference.provider}`;refWrap.append(ref,source);}else{const missing=document.createElement('span');missing.className='command-reference-missing';missing.textContent=getMissingReferenceLabel();refWrap.append(missing);}card.append(refWrap);grid.append(card);});}
  search.addEventListener('input',render);category.addEventListener('change',render);window.addEventListener('academy:language',()=>{buildCategories();render();});buildCategories();render();return commands;
}
